export const SEARCH_MOVIE_START = "SEARCH_MOVIE_START"
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR"
export const SEARCH_MOVIE_COMPLETE = "SEARCH_MOVIE_COMPLETE"

export const SEARCH_MOVIE_BY_ID_START = "SEARCH_MOVIE_BY_ID_START"
export const SEARCH_MOVIE_BY_ID_ERROR = "SEARCH_MOVIE_BY_ID_ERROR"
export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIE_BY_ID_COMPLETE"

export const SET_LOGGED_USER = "SET_LOGGED_USER"
export const SET_USER_TODO_LIST = "SET_USER_TODO_LIST"
export const UPDATE_DOING = "UPDATE_DOING"

// export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIE_BY_ID_COMPLETE"
// export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIE_BY_COMPLETE"
